### ISSUE TITLE
FR12. Job Seeker Verification

### ISSUE THREAD

**Issue by SiddPpatel** [WSU-4110/Lawn-Care#12]
|FR12. Job Seeker Verification|
|---|
|**Goal:** Makes it so the Job Seeker is confirmed as a verified lawn care provider.
|**Stakeholders:** Employees
|**Description:** The Job seekers upload proof through uploading a lawn care license to prove that they are a certified lawn care provider.
|**Origin:** During group meeting, as a form of security for our users.
| **Version:** 1.6  |
|**Date:** 09/11/2019
|  **Priority:** 17|

**Comment by IshanPatel444** [comment]
Achieved.
