### ISSUE TITLE
FR22. Administrator view

### ISSUE THREAD

**Issue by SiddPpatel** [WSU-4110/Lawn-Care#22]
|FR22. Administrator view|
|---|
|**Goal**:Administrators will be able to approve and delete job seeker profiles
|**Stakeholders**:Administrator
|**Description**:When an administrator views information about job seekers, they will have the ability to approve or delete job seeker profiles. Administrators will see buttons to perform those actions on the worker profile
|**Origin**:Discovered during team discussion on job seeker needs
|**Version**:1.21
|**Date**:9/18/2019
|**Priority**:16

**Comment by IshanPatel444** [comment]
Achieved.
