### ISSUE TITLE
NFR2. Privacy Policy

### ISSUE THREAD

**Issue by SiddPpatel** [WSU-4110/Lawn-Care#24]
|NFR2. Privacy Policy|
|---|
|**Goal**:App should not disclose data with other parties
|**Stakeholders**:customer
|**Description**:Personal information, name, email address, phone number
|**Origin**:Privacy revie
|**Version**:1.22
|**Date**:9/17/19
|**Priority**:

**Comment by IshanPatel444** [comment]
Achieved Privacy policy.
