### ISSUE TITLE
NFR3. Availability

### ISSUE THREAD

**Issue by SiddPpatel** [WSU-4110/Lawn-Care#25]
|NFR3. Availability|
|---|
|**Goal**:system should always be available
|**Stakeholders**:everyon
|**Description**:maintenance should only be at 12am-5am to maintain user availability
|**Origin**:maintenance of app revie
|**Version**:1.23
|**Date**:9/17/19
|**Priority**:

**Comment by IshanPatel444** [comment]
@4/7 availability achieved,
