### ISSUE TITLE
NFR4. Speed

### ISSUE THREAD

**Issue by SiddPpatel** [WSU-4110/Lawn-Care#26]
|NFR4. Speed|
|---|
|**Goal**:Faster Login
|**Stakeholders**:Develope
|**Description**:As soon as the user starts typing it needs to start looking into Database
|**Origin**:team meetings
|**Version**:1.24
|**Date**:9/17/2019
|**Priority**:

**Comment by IshanPatel444** [comment]
softwere is achieving the speed goal.
